module.exports = [
  "jack daniel's",
  "glenfiddich",
  "macallan",
  "jameson",
  "chivas regal",
  "laphroaig",
  "talisker",
  "maker's mark",
  "absolut",
  "grey goose",
  "belvédère",
  "smirnoff",
  "tanqueray",
  "bombay sapphire",
  "hendrick's",
  "gordon's",
  "josé cuervo",
  "patron",
  "don julio",
  "hennessy",
  "remy martin",
  "courvoisier",
  "martell",
  "ricard",
  "pernod",
  "martini",
  "noilly prat",
  "byrrh",
  "dubonnet",
  "cointreau",
  "grand marnier",
  "baileys",
  "jägermeister",
  "disaronno",
  "kahlúa",
  "rossi d'asiago",
  "aperol",
  "campari",
  "molinari",
  "get 27",
  "malibu",
  "southern comfort",
  "barcardi",
  "havana club",
  "captain morgan",
  "diplomatico",
  "zacapa",
  "damoiseau",
  "trois rivières",
  "clément",
  "mount gay",
  "appleton estate",
  "plantation",
  "kraken",
  "saint james",
  "bundaberg",
  "don papa",
  "ron barcelo",
  "brugal",
  "matusalem",
  "flor de caña",
  "el dorado",
  "buffalo trace",
  "jim beam",
  "woodford reserve",
  "bulleit",
  "wild turkey",
  "bushmills",
  "tullamore dew",
  "redbreast",
  "nikka",
  "yamamazaki",
  "hibiki",
  "hakushu",
  "glenmorangie",
  "balvenie",
  "lagavulin",
  "ardbeg",
  "bowmore",
  "monkey 47",
  "roku",
  "beefeater",
  "sierra tequila",
  "olmeca",
  "espolon",
  "herradura",
  "1800 tequila",
  "casamigos",
  "veuve clicquot",
  "moët & chandon",
  "dom pérignon",
  "ruinart",
  "krug",
  "taittinger",
  "bollinger",
  "pommery",
  "lanson",
  "piper-heidsieck",
  "mumm",
  "perrier-jouët",
  "laurent-perrier",
  "roederer",
  "tsarine",
  "nicolas feuillatte",
  "canard-duchêne",
  "pol roger",
  "deutz",
  "gosset",
  "ayala",
  "heineken",
  "kronenbourg",
  "1664",
  "leffe",
  "grimbergen",
  "desperados",
  "corona",
  "stella artois",
  "budweiser",
  "guinness",
  "hoegaarden",
  "affligem",
  "pelforth",
  "chouffe",
  "duvel",
  "kwak",
  "tripel karmeliet",
  "chimay",
  "orval",
  "westmalle",
  "rochefort",
  "vedett",
  "peroni",
  "san miguel",
  "asahi",
  "tsingtao",
  "tiger",
  "foster's",
  "carlsberg",
  "tuborg",
  "amstel",
  "beck's",
  "skol",
  "brahma",
  "quilmes",
  "aguila",
  "polar",
  "presidente",
  "toña",
  "gallo",
  "balboa",
  "cristal",
  "cusqueña",
  "paceña",
  "huari",
  "sol",
  "tecate",
  "modelo",
  "dos equis",
  "pacifico",
  "victoria",
  "bohemia",
  "carta blanca",
  "indio",
  "bavaria",
  "bud light",
  "coors light",
  "miller lite",
  "blue moon",
  "samuel adams",
  "sierra nevada",
  "lagunitas",
  "founders",
  "brewdog",
  "erdinger",
  "franziskaner",
  "paulaner",
  "weihenstephaner",
  "löwenbräu",
  "hofbräu",
  "augustiner",
  "spaten",
  "bitburger",
  "warsteiner",
  "krombacher",
  "jupiler",
  "maes",
  "primus",
  "mort subite",
  "lindemans",
  "cantillon",
  "boon",
  "3 fonteinen",
  "rodenbach",
  "saint feuillien",
  "maredsous",
  "val-dieu",
  "floreffe",
  "ter dolen",
  "herkenrode",
  "postel",
  "tongerlo",
  "keizersberg",
  "park",
  "steenbrugge",
  "bornem",
  "kapittel",
  "ramée",
  "st bernardus",
  "westvleteren",
  "achel",
  "la trappe",
  "zundert",
  "tynt meadow",
  "spencer",
  "tre fontane",
  "mount st bernard",
  "engelszell",
  "cardeña",
  "mont des cats",
  "san pietro",
  "grolsch",
  "kilkenny",
  "smithwicks",
  "harp",
  "murphy's",
  "beamish",
  "caffrey's",
  "newcastle brown ale",
  "carling",
  "xxxx gold",
  "victoria bitter",
  "carlton draught",
  "tooheys",
  "coopers",
  "cascade",
  "james squire",
  "little creatures",
  "fat yak",
  "stone & wood",
  "balter",
  "pirate life",
  "mountain goat",
  "4 pines",
  "green beacon",
  "your mates",
  "black hops",
  "gage roads",
  "matso's",
  "feral",
  "nail",
  "colonial",
  "cheeky monkey",
  "eagle bay",
  "bootleg",
  "rocky ridge",
  "wild hop",
  "beerfarm",
  "shelter",
  "froth",
  "whalers",
  "gascoyne",
  "shark bay",
  "finlay's",
  "geraldton",
  "beaten track",
  "kalgoorlie",
  "lucky bay",
  "boundary island",
  "thorny devil",
  "king road",
  "blasta",
  "nowhereman",
  "bright tank",
  "seasonal",
  "whipper snapper",
  "sin gin",
  "old young's",
  "republic",
  "hippocampus",
  "swan",
  "emu",
  "redback",
  "matilda bay",
  "bluetongue",
  "resch's",
  "tooth's",
  "kb",
  "abbots",
  "melbourne bitter",
  "cascade stout",
  "mercury",
  "strongbow",
  "5 seeds",
  "somersby",
  "bulmers",
  "magners",
  "rekorderlig",
  "kopperberg",
  "orchard thieves",
  "woodchuck",
  "angry orchard",
  "savanna",
  "hunters",
  "windhoek",
  "castle",
  "lion",
  "hansa",
  "tafel",
  "2m",
  "laurentina",
  "manica",
  "txilar",
  "cuca",
  "nocal",
  "ngola",
  "33 export",
  "castel",
  "beaufort",
  "gazelle",
  "flag",
  "star",
  "club",
  "gulder",
  "legend",
  "hero",
  "life",
  "goldberg",
  "origin",
  "satzenbrau",
  "dubic",
  "turbo king",
  "king",
  "grand",
  "top",
  "hi-malt",
  "malta guinness",
  "amstel malta",
  "maltina",
  "grand malt",
  "maltex",
  "super malt",
  "powermalt",
  "vitamalt",
  "pony malt",
  "malta gold",
  "malta india",
  "schin",
  "kaiser",
  "glacial",
  "antarctica",
  "original",
  "serra malte",
  "xingu",
  "eisenbahn",
  "baden baden",
  "devassa",
  "schincariol",
  "conti",
  "cerpa",
  "tijuca",
  "amazon beer",
  "dado bier",
  "coruja",
  "way beer",
  "bodebrown",
  "tupiniquim",
  "peron",
  "moretti",
  "ichnusa",
  "nastro azzurro",
  "menabrea",
  "poretti",
  "dreher",
  "raffo",
  "messina",
  "forst",
  "pedavena",
  "castello",
  "wührer",
  "von wunster",
  "sans souci",
  "prinz",
  "itala pilsen",
  "mahou",
  "cruzcampo",
  "estrella damm",
  "ambar",
  "alhambra",
  "vol damm",
  "inedit",
  "daura",
  "keler",
  "oro",
  "turia",
  "victoria malaga",
  "el águila",
  "buckler",
  "shandy carib",
  "carib",
  "stag",
  "mackeson",
  "red stripe",
  "dragon stout",
  "banks",
  "wadadli",
  "kubuli",
  "hairoun",
  "piton",
  "kalik",
  "sands",
  "high rock",
  "bush crack",
  "strong back",
  "prestige",
  "toro",
  "medalla",
  "silver key",
  "magna",
  "chairman's reserve",
  "bounty",
  "admiral rodney",
  "denros",
  "marigot bay",
  "elements",
  "toz",
  "kwéyòl",
  "castries",
  "j.m.",
  "bielle",
  "père labat",
  "longueteau",
  "karukera",
  "bologne",
  "reimonenq",
  "montebello",
  "damien rougier",
  "bellevue",
  "depaz",
  "neisson",
  "dillon",
  "bally",
  "hse",
  "la mauny",
  "hardy",
  "favorite",
  "braud & quennesson",
  "baie des trésors",
  "a1710",
  "isautier",
  "savanna",
  "rivière du mât",
  "châtel",
  "chamarel",
  "new grove",
  "lazy dodo",
  "saint aubin",
  "emperor",
  "penny blue",
  "pink pigeon",
  "beach house",
  "arcane",
  "bougainville",
  "starr",
  "blue mauritius",
  "gold of mauritius",
  "turquoise bay",
  "ti rhum",
  "dzama",
  "mangoustan",
  "casanera",
  "altore",
  "mavela",
  "corsaire",
  "santero",
  "mulata",
  "varadero",
  "caney",
  "santiago de cuba",
  "legendario",
  "eminente",
  "perla del norte",
  "cubay",
  "conde de cuba",
  "ritual",
  "botran",
  "seco herrerano",
  "carta vieja",
  "panama club",
  "malecon",
  "zafra",
  "origenes",
  "cacique",
  "pampero",
  "santa teresa",
  "carupano",
  "veroes",
  "estelar",
  "sailor jerry",
  "goslings",
  "cruzan",
  "calico jack",
  "bones",
  "pyrat",
  "pusser's",
  "soggy dollar",
  "calypso",
  "tortola",
  "brinley gold",
  "clifton estate",
  "cane spirits",
  "belmont estate",
  "westerhall",
  "clarke's court",
  "river antoine",
  "rivers",
  "carriacou",
  "windward",
  "blue bay",
  "green island",
  "equiano",
  "mhoba",
  "whistler",
  "zulu",
  "copeland",
  "diep 9",
  "naga",
  "chalong bay",
  "issan",
  "phraya",
  "sangsom",
  "mekhong",
  "tanduay",
  "nine leaves",
  "ryoma",
  "santa maria",
  "helios",
  "ogasawara",
  "cor cor",
  "ie rum",
  "kumejima",
  "amami",
  "kokuto",
  "shima",
  "teeda",
  "makito",
  "beenleigh",
  "inner circle",
  "holey dollar",
  "hooch",
  "jimmy rum",
  "brix",
  "lord byron",
  "nil desperandum",
  "kalki moon",
  "husk",
  "gunnery",
  "illegal",
  "dead man's fingers",
  "lugger",
  "burning barn",
  "rockstar",
  "scratch",
  "english harbour",
  "cavalier",
  "kokocaribe",
  "saint lucia distillers",
];
